services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
        - /tmp/docker/
  proxy:
      build: .
      volumes_from:
        - tmp
      ports:
        - 5000:5000/udp 
        - 5000:5000
      extra_hosts:
        - "host.docker.internal:host-gateway"
  redis:
      image: redis
      command: redis-server /etc/redis.conf
      volumes:
        - ./redis.conf:/etc/redis.conf
      volumes_from:
        - tmp

volumes:
  redis:
