services:
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
        - redis
  proxy:
      build: .
      volumes:
          - redis:/tmp/docker 
      ports:
        - 5000:5000/udp 
        - 5000:5000
      extra_hosts:
        - "host.docker.internal:host-gateway"
  redis:
      image: redis
      command: redis-server /etc/redis.conf
      volumes:
          - ./redis.conf:/etc/redis.conf
          - redis:/tmp/docker 

volumes:
  redis:
